keys:
  - &host_key age1q5a9ckmdn8m7u3ap4k7kngkwjxd6up860z9hjdsmkas2mvg6f9gqfuvvdh

creation_rules:
  - path_regex: modules/home/homeLab/secrets\.yaml$
    key_groups:
      - age:
          - *host_key
